'use client'

import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import remarkGfm from 'remark-gfm';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

import { AlertTriangle } from 'lucide-react';

interface MarkdownRendererProps {
    content: string;
}

export function MarkdownRenderer({ content }: MarkdownRendererProps) {
    // Extract the grounded-facts disclaimer if present
    const disclaimerRegex = /(?:IMPORTANT:\s*)?(This section contains a disclaimer[\s\S]*?grounded information available in the source material\.)/gi;
    const match = content.match(disclaimerRegex);
    const disclaimer = match ? match[1] || match[0] : null;
    
    // Remove the disclaimer from the main markdown flow so we can render it as a custom banner
    const contentToProcess = disclaimer ? content.replace(disclaimer, '') : content;

    // Preprocess common LaTeX delimiters generated by LLMs to standard markdown math delimiters
    // Also replace Unicode subscript/superscript chars that KaTeX can't handle in text mode
    const processedContent = contentToProcess
        .replace(/\\\[/g, '$$$$')
        .replace(/\\\]/g, '$$$$')
        .replace(/\\\(/g, '$')
        .replace(/\\\)/g, '$')
        // Sometimes the backslash gets stripped, leaving just [ \begin{...} \end{...} ]
        .replace(/\[\s*(\\begin\{[^}]+\}[\s\S]*?\\end\{[^}]+\})\s*\]/g, '$$$$\n$1\n$$$$')
        // Strip backend citation markers (e.g. [Title] concept=concept.xyz field=texts locator=0)
        .replace(/\[.*?\] concept=.*? field=\S+ locator=\S+( object=\S+)?/g, '')
        // Clean up dangling "Citations:" or "Sources:" prefixes left behind
        .replace(/(?:Citations|Sources):\s*(?=\n|$)/gi, '')
        // Replace Unicode subscript/superscript with LaTeX equivalents
        .replace(/₀/g, '_0').replace(/₁/g, '_1').replace(/₂/g, '_2')
        .replace(/₃/g, '_3').replace(/₄/g, '_4').replace(/₅/g, '_5')
        .replace(/₆/g, '_6').replace(/₇/g, '_7').replace(/₈/g, '_8').replace(/₉/g, '_9')
        .replace(/⁺/g, '^+').replace(/⁻/g, '^-')
        // Non-breaking hyphen → regular hyphen
        .replace(/\u2011/g, '-');

    return (
        <div className="flex flex-col gap-4">
            {disclaimer && (
                <div className="bg-amber-900/20 border border-amber-900/50 rounded-xl p-4 flex gap-3 text-amber-200/90 shadow-sm mt-2 mb-2">
                    <AlertTriangle className="w-5 h-5 shrink-0 text-amber-500 mt-0.5" />
                    <p className="m-0 text-sm leading-relaxed">{disclaimer}</p>
                </div>
            )}
            <div className="prose prose-invert prose-slate max-w-none prose-p:leading-relaxed prose-pre:bg-slate-900 prose-pre:border prose-pre:border-slate-800 prose-headings:text-slate-100 prose-a:text-blue-400">
                <ReactMarkdown 
                    remarkPlugins={[remarkMath, remarkGfm]} 
                    rehypePlugins={[rehypeKatex]}
                >
                    {processedContent}
                </ReactMarkdown>
            </div>
        </div>
    );
}
