"""Simple, reliable session store for v2.

Design principles (inspired by how ChatGPT/Claude handle sessions):
1. Session is created WHEN USER CLICKS "New Chat" (not on page load)
2. Session ID is always generated by the SERVER
3. Frontend NEVER generates session IDs
4. Session data is always loaded from backend on page load
5. If session doesn't exist, show empty chat (don't create one)
"""

from __future__ import annotations

import json
import sqlite3
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field


class Message(BaseModel):
    """A single message in a conversation."""
    role: str  # "user" or "assistant"
    content: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    sources: list[dict] = Field(default_factory=list)
    citations: list[dict] = Field(default_factory=list)


class ChatSession(BaseModel):
    """A chat session — simple and clean."""
    id: str
    user_id: str = "anonymous"
    title: str = "New Chat"
    messages: list[Message] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class SessionStore:
    """SQLite-backed session store.

    Usage:
        store = SessionStore()

        # Create new session (called when user clicks "New Chat")
        session = store.create("math_session")

        # Load existing session
        session = store.get("abc-123")

        # Add message
        store.add_message("abc-123", Message(role="user", content="What is a matrix?"))
        store.add_message("abc-123", Message(role="assistant", content="A matrix is..."))

        # List sessions (only non-empty)
        sessions = store.list()
    """

    def __init__(self, db_path: str = "data/chat_sessions.db"):
        self._db_path = db_path
        self._init_db()

    def _init_db(self):
        """Create table if it doesn't exist."""
        Path(self._db_path).parent.mkdir(parents=True, exist_ok=True)
        with sqlite3.connect(self._db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS chat_sessions (
                    id TEXT PRIMARY KEY,
                    user_id TEXT DEFAULT 'anonymous',
                    data TEXT NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
            # Create index for faster queries
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id
                ON chat_sessions(user_id)
            """)

    def create(self, title: str = "New Chat", user_id: str = "anonymous") -> ChatSession:
        """Create a new session with server-generated ID."""
        session = ChatSession(
            id=str(uuid.uuid4()),
            title=title,
            user_id=user_id,
        )
        self._save(session)
        return session

    def get(self, session_id: str) -> Optional[ChatSession]:
        """Get session by ID. Returns None if not found."""
        with sqlite3.connect(self._db_path) as conn:
            row = conn.execute(
                "SELECT data FROM sessions WHERE id = ?",
                (session_id,)
            ).fetchone()
            if row:
                return ChatSession.model_validate_json(row[0])
        return None

    def add_message(self, session_id: str, message: Message) -> Optional[ChatSession]:
        """Add a message to session. Updates title from first user message."""
        session = self.get(session_id)
        if not session:
            return None

        session.messages.append(message)
        session.updated_at = datetime.now(timezone.utc).isoformat()

        # Update title from first user message
        if message.role == "user" and session.title == "New Chat":
            session.title = message.content[:50]

        self._save(session)
        return session

    def list(self, user_id: str = "anonymous") -> list[dict]:
        """List all sessions for a user (only those with messages)."""
        sessions = []
        with sqlite3.connect(self._db_path) as conn:
            for row in conn.execute(
                "SELECT data FROM chat_sessions WHERE user_id = ? ORDER BY updated_at DESC",
                (user_id,)
            ):
                session = ChatSession.model_validate_json(row[0])
                if len(session.messages) > 0:
                    sessions.append({
                        "id": session.id,
                        "title": session.title,
                        "updated_at": session.updated_at,
                        "message_count": len(session.messages),
                    })
        return sessions

    def delete(self, session_id: str) -> bool:
        """Delete a session."""
        with sqlite3.connect(self._db_path) as conn:
            cursor = conn.execute("DELETE FROM chat_sessions WHERE id = ?", (session_id,))
            return cursor.rowcount > 0

    def cleanup(self) -> int:
        """Delete sessions with no messages."""
        with sqlite3.connect(self._db_path) as conn:
            cursor = conn.execute("SELECT id, data FROM chat_sessions")
            deleted = 0
            for row in cursor.fetchall():
                session = ChatSession.model_validate_json(row[1])
                if len(session.messages) == 0:
                    conn.execute("DELETE FROM chat_sessions WHERE id = ?", (row[0],))
                    deleted += 1
            return deleted

    def _save(self, session: ChatSession) -> None:
        """Save session to database."""
        with sqlite3.connect(self._db_path) as conn:
            conn.execute(
                """INSERT INTO chat_sessions (id, user_id, data, updated_at)
                   VALUES (?, ?, ?, CURRENT_TIMESTAMP)
                   ON CONFLICT(id) DO UPDATE SET
                   data=excluded.data, updated_at=CURRENT_TIMESTAMP""",
                (session.id, getattr(session, 'user_id', 'anonymous'), session.model_dump_json())
            )
